# BlockDB Configuration
[database]
data_dir = "./blockdb_data"
memtable_size_limit = 67108864  # 64MB
wal_sync_interval = 1000        # milliseconds
compaction_threshold = 4
blockchain_batch_size = 1000

[server]
host = "127.0.0.1"
port = 8080
worker_threads = 4

[auth]
enabled = true
require_auth_for_reads = false
session_duration_hours = 24
password_min_length = 8
password_require_special_chars = true
max_failed_attempts = 5
account_lockout_duration_minutes = 30
admin_users = ["admin"]

[cluster]
node_id = "node1"
heartbeat_interval = 150        # milliseconds
election_timeout = 300          # milliseconds
enable_transactions = true
transaction_timeout = 30        # seconds

[logging]
level = "info"
file = "./logs/blockdb.log"

[api]
enable_cors = true
enable_compression = true
max_connections = 1000
request_timeout = 30            # seconds