# BlockDB Docker Configuration
[database]
data_dir = "/var/lib/blockdb"
memtable_size_limit = 67108864  # 64MB
wal_sync_interval = 1000
compaction_threshold = 4
blockchain_batch_size = 1000

[server]
host = "0.0.0.0"
port = 8080
worker_threads = 4

[cluster]
node_id = "node1"
heartbeat_interval = 150
election_timeout = 300
enable_transactions = true
transaction_timeout = 30

# Cluster peers (will be overridden by environment variables)
peers = []

[logging]
level = "info"
file = "/var/log/blockdb/blockdb.log"